BEGIN TRANSACTION;

DROP TABLE EXECUTION_DETAILS;
DROP TABLE LOADING_EXECUTION;
DROP TABLE TASK_REQUESTS;
DROP TABLE LOAD_REQUEST;
DROP TABLE LOAD_TASK;

DELETE FROM SCHEMA where scriptNumber = '0001';

COMMIT;