BEGIN TRANSACTION;
CREATE TABLE LOAD_REQUEST02ca
(
    id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    type varchar(6) NOT NULL,
    url varchar NOT NULL,
    timeout integer
);
INSERT INTO LOAD_REQUEST02ca(id, type, url, timeout) SELECT id, type, url, timeout FROM LOAD_REQUEST;
DROP TABLE LOAD_REQUEST;
ALTER TABLE LOAD_REQUEST02ca RENAME TO LOAD_REQUEST;

DELETE FROM SCHEMA where scriptNumber = '0002';

COMMIT;